config/routes.rb
ZoodyNews::Application.routes.draw do
  resources :news_items

  resources :news_links

end

app/models/news_item.rb
class NewsItem < ActiveRecord::Base
end

app/models/news_link.rb
class NewsLink < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/news_items_controller.rb
class NewsItemsController < ApplicationController
  # GET /news_items
  # GET /news_items.xml
  def index
    @news_items = NewsItem.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news_items }
    end
  end

  # GET /news_items/1
  # GET /news_items/1.xml
  def show
    @news_item = NewsItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news_item }
    end
  end

  # GET /news_items/new
  # GET /news_items/new.xml
  def new
    @news_item = NewsItem.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @news_item }
    end
  end

  # GET /news_items/1/edit
  def edit
    @news_item = NewsItem.find(params[:id])
  end

  # POST /news_items
  # POST /news_items.xml
  def create
    @news_item = NewsItem.new(params[:news_item])

    respond_to do |format|
      if @news_item.save
        format.html { redirect_to(@news_item, :notice => 'News item was successfully created.') }
        format.xml  { render :xml => @news_item, :status => :created, :location => @news_item }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @news_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /news_items/1
  # PUT /news_items/1.xml
  def update
    @news_item = NewsItem.find(params[:id])

    respond_to do |format|
      if @news_item.update_attributes(params[:news_item])
        format.html { redirect_to(@news_item, :notice => 'News item was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @news_item.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /news_items/1
  # DELETE /news_items/1.xml
  def destroy
    @news_item = NewsItem.find(params[:id])
    @news_item.destroy

    respond_to do |format|
      format.html { redirect_to(news_items_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/news_links_controller.rb
class NewsLinksController < ApplicationController
  # GET /news_links
  # GET /news_links.xml
  def index
    @news_links = NewsLink.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @news_links }
    end
  end

  # GET /news_links/1
  # GET /news_links/1.xml
  def show
    @news_link = NewsLink.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @news_link }
    end
  end

  # GET /news_links/new
  # GET /news_links/new.xml
  def new
    @news_link = NewsLink.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @news_link }
    end
  end

  # GET /news_links/1/edit
  def edit
    @news_link = NewsLink.find(params[:id])
  end

  # POST /news_links
  # POST /news_links.xml
  def create
    @news_link = NewsLink.new(params[:news_link])

    respond_to do |format|
      if @news_link.save
        format.html { redirect_to(@news_link, :notice => 'News link was successfully created.') }
        format.xml  { render :xml => @news_link, :status => :created, :location => @news_link }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @news_link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /news_links/1
  # PUT /news_links/1.xml
  def update
    @news_link = NewsLink.find(params[:id])

    respond_to do |format|
      if @news_link.update_attributes(params[:news_link])
        format.html { redirect_to(@news_link, :notice => 'News link was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @news_link.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /news_links/1
  # DELETE /news_links/1.xml
  def destroy
    @news_link = NewsLink.find(params[:id])
    @news_link.destroy

    respond_to do |format|
      format.html { redirect_to(news_links_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/news_items_helper.rb
module NewsItemsHelper
end

app/helpers/news_links_helper.rb
module NewsLinksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ZoodyNews</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/news_items/_form.html.erb
<%= form_for(@news_item) do |f| %>
  <% if @news_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_item.errors.count, "error") %> prohibited this news_item from being saved:</h2>

      <ul>
      <% @news_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :added_on %><br />
    <%= f.datetime_select :added_on %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :added_by %><br />
    <%= f.text_area :added_by %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_items/edit.html.erb
<h1>Editing news_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_item %> |
<%= link_to 'Back', news_items_path %>

app/views/news_items/index.html.erb
<h1>Listing news_items</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Added on</th>
    <th>Content</th>
    <th>Added by</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news_items.each do |news_item| %>
  <tr>
    <td><%= news_item.title %></td>
    <td><%= news_item.added_on %></td>
    <td><%= news_item.content %></td>
    <td><%= news_item.added_by %></td>
    <td><%= news_item.active %></td>
    <td><%= link_to 'Show', news_item %></td>
    <td><%= link_to 'Edit', edit_news_item_path(news_item) %></td>
    <td><%= link_to 'Destroy', news_item, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New News item', new_news_item_path %>

app/views/news_items/new.html.erb
<h1>New news_item</h1>

<%= render 'form' %>

<%= link_to 'Back', news_items_path %>

app/views/news_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news_item.title %>
</p>

<p>
  <b>Added on:</b>
  <%= @news_item.added_on %>
</p>

<p>
  <b>Content:</b>
  <%= @news_item.content %>
</p>

<p>
  <b>Added by:</b>
  <%= @news_item.added_by %>
</p>

<p>
  <b>Active:</b>
  <%= @news_item.active %>
</p>


<%= link_to 'Edit', edit_news_item_path(@news_item) %> |
<%= link_to 'Back', news_items_path %>

app/views/news_links/_form.html.erb
<%= form_for(@news_link) do |f| %>
  <% if @news_link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@news_link.errors.count, "error") %> prohibited this news_link from being saved:</h2>

      <ul>
      <% @news_link.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :added_by %><br />
    <%= f.text_field :added_by %>
  </div>
  <div class="field">
    <%= f.label :added_on %><br />
    <%= f.datetime_select :added_on %>
  </div>
  <div class="field">
    <%= f.label :video_link %><br />
    <%= f.text_field :video_link %>
  </div>
  <div class="field">
    <%= f.label :image_link %><br />
    <%= f.text_field :image_link %>
  </div>
  <div class="field">
    <%= f.label :active %><br />
    <%= f.text_field :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/news_links/edit.html.erb
<h1>Editing news_link</h1>

<%= render 'form' %>

<%= link_to 'Show', @news_link %> |
<%= link_to 'Back', news_links_path %>

app/views/news_links/index.html.erb
<h1>Listing news_links</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Added by</th>
    <th>Added on</th>
    <th>Video link</th>
    <th>Image link</th>
    <th>Active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @news_links.each do |news_link| %>
  <tr>
    <td><%= news_link.title %></td>
    <td><%= news_link.added_by %></td>
    <td><%= news_link.added_on %></td>
    <td><%= news_link.video_link %></td>
    <td><%= news_link.image_link %></td>
    <td><%= news_link.active %></td>
    <td><%= link_to 'Show', news_link %></td>
    <td><%= link_to 'Edit', edit_news_link_path(news_link) %></td>
    <td><%= link_to 'Destroy', news_link, :confirm => 'Do you want to delete, Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add New', new_news_link_path %>

app/views/news_links/new.html.erb
<h1>New news_link</h1>

<%= render 'form' %>

<%= link_to 'Back', news_links_path %>

app/views/news_links/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @news_link.title %>
</p>

<p>
  <b>Added by:</b>
  <%= @news_link.added_by %>
</p>

<p>
  <b>Added on:</b>
  <%= @news_link.added_on %>
</p>

<p>
  <b>Video link: </b><%= @news_link.video_link %>
  <p><iframe title="YouTube video player" width="425" height="349" src="http://www.youtube.com/embed/<%= @news_link.video_link %>?rel=0" frameborder="0" allowfullscreen></iframe></p>
</p>

<p>
  <b>Image link:</b><%= @news_link.image_link %>
  <p><img src = "http://img.youtube.com/vi/<%= @news_link.image_link %>/1.jpg" /></p>
</p>

<p>
  <b>Active: (0 = true, 1 = false)</b>
  <%= @news_link.active %>
</p>


<%= link_to 'Edit', edit_news_link_path(@news_link) %> |
<%= link_to 'Back', news_links_path %>